name: CI for Vite Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # O la versión que prefieras

    # Limpia dependencias e instala nuevamente
    - name: Clean install
      run: |
        rm -rf node_modules
        rm -f package-lock.json
        npm install

    # Agrega permisos de ejecución
    - name: Add execution permissions
      run: chmod +x ./node_modules/.bin/vite

    - name: Build project
      run: npm run build
